- name: install git from homebrew
  homebrew:
    name: git
    state: present

- name: symlink dotfiles
  file:
    src: "{{ ansible_env.PWD }}/roles/git/files/{{ item }}"
    path: "~/.{{ item }}"
    state: link
    force: yes
  loop:
    - gitconfig
