- name: install vim from homebrew
  homebrew:
    name: vim
    state: present

- name: symlink .vimrc
  file:
    src: "{{ ansible_env.PWD }}/roles/vim/files/{{ item }}"
    path: "~/.{{ item }}"
    state: link
    force: yes
  loop:
    - vimrc

- name: symlink plug.vim
  file:
    src: "{{ ansible_env.PWD }}/roles/vim/files/{{ item }}"
    path: "~/.cache/vim/autoload/plug.vim"
    state: link
    force: yes
  loop:
    - plugvim

- name: install plugins
  command: vim +"PlugInstall --sync" +qa